### ISSUE TITLE
Move away from coffeescript-php

### ISSUE THREAD

**Issue by axelson** [vendethiel/Sprockets-PHP#35]
CoffeeScript-PHP only support CoffeeScript 1.3.1, but the latest CoffeeScript version is 1.9.1. Additionaly CoffeeScript-PHP has no plans to upgrade the version of CoffeeScript they support [1] and the last commit was in 2012. Hence CoffeeScript-PHP should be replaced with something else, maybe a direct call to the CoffeeScript executable?

[1] https://github.com/alxlit/coffeescript-php/issues/24

**Comment by vendethiel** [comment]
Sounds like I'll need to do that, yes.
