### ISSUE TITLE
Possibility for better configuration possibilities?

### ISSUE THREAD

**Issue by ahukkanen** [vendethiel/Sprockets-PHP#36]
Is there any possibility this library could be made more configurable? In particular, I mean the processing filters that different types of files are passed through:
https://github.com/vendethiel/Sprockets-PHP/blob/master/lib/Sprockets/File.php#L73-L74

We're currently discussing about including this in another project but the problem is that it uses different less compier because of problems in integrating the lessphp library into the other project. So, in this particular case we would want to use a different filter for the "less" file type.

It is of course possible by forking this repo but they probably want to avoid that.

I think in the ruby equivalent it is possible to configure these with ease:
https://github.com/rails/sprockets/blob/master/lib/sprockets.rb#L142-L143
https://github.com/metaskills/less-rails/blob/master/lib/less/rails/railtie.rb#L18

**Comment by vendethiel** [comment]
It's possible right now by having your own `Sprockets\Filter\Less` class, but indeed not very nice.

I'll look at a way. I probably need to remove lessphp anyhow and use the js version...

**Comment by ahukkanen** [comment]
Ok, thanks for the heads up and info. Yeah, that would not be very convenient way of hacking the class.

Bummer, I actually initially thought this was fully PHP based and looking the code more closely now, I'm noticing it's not. That'll probably be a major issue in integrating this one, so we'll probably need to check for other solutions.

**Comment by vendethiel** [comment]
;-) that's why I wanted the library, but it's just unworkable. Coffee-php hasn't been maintained in 2years , sassphp same, lessphp same. This doesn't work.

**Comment by ahukkanen** [comment]
Yeah, I know and that's bad. Maybe node.js will be installed on all machines in the future by default...

Fortunately I personally hate coffee script, so that doesn't bother me. For less, there are more recently updated solutions, though:
https://github.com/oyejorge/less.php

For sass, I don't think there are any plain PHP libraries that would be actively maintained. But there are few alternatives that are more recently updated like leafo/scssphp. Too bad these don't seem too active either.

Seems like the PHP community in general is more geared towards using less.

**Comment by vendethiel** [comment]
> leafo/scssphp

I use sass, not scss :-).


> For less, there are more recently updated solutions, though:

Nice! I'm sorry, I'm too tired tonight to take a look, but adding such an option should be easy.

Btw, just in case -- the library doesn't need nodejs or anything "external" if you don't plan to use those filters.

**Comment by ahukkanen** [comment]
Oh, OK. I thought the old sass format was dying so it might be the reason why there are no up to date alternatives to it in PHP. The official sass website also primarily offers you scss in the guides.

I noticed that. We'll need to discuss with the project. But we'd need at least less for the project and the primary reason to integrate this would be to allow people easily also swap to scss/sass if they want. Plus I would also see it as a benefit to use the sprockets type includes.

Thanks for the consideration! And keep this updated if you end up doing any changes regarding this.

**Comment by vendethiel** [comment]
I will. Just probably not today, because I don't have the energy for it.

**Comment by vendethiel** [comment]
Ah, I just remember that actually exists, it's just not documented.

Just call
```php
$pipeline->registerFilter('ext', 'class\name');
```

The class needs to implement `Sprockets\Filter\Base`

**Comment by vendethiel** [comment]
I added a test! e15038fe92585b53742ac8d64fc7ae7ff01c1dde

**Comment by ahukkanen** [comment]
Thanks! Looks great!
